services:
  build-app:
    container_name: build-app
    restart: always
    build: .
    ports:
      - "801:80"
    
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup build-app